### ISSUE TITLE
Deprecated in iOS 12.0

### ISSUE THREAD

**Issue by nebucaz** [granoff/Strongbox#13]
in `Strongbox.swift`

Line 73
`let archiver = NSKeyedArchiver(forWritingWith: data)`
'init(forWritingWith:)' was deprecated in iOS 12.0: Use -initRequiringSecureCoding: instead

and Line 95:
`let unarchiver = NSKeyedUnarchiver(forReadingWith: data as Data)`
'init(forReadingWith:)' was deprecated in iOS 12.0: Use -initForReadingFromData:error: instead

**Comment by granoff** [comment]
Fixed in v0.5.2

**Comment by clintonb** [comment]
This issue still exists.

https://github.com/granoff/Strongbox/blob/2abad48958b94f7d474026add8f809aceb47050d/Strongbox/Classes/Strongbox.swift#L125
